{% set name = "imagehash" %}
{% set version = "4.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ImageHash-{{ version }}.tar.gz
  sha256: a4af957814bc9832d9241247ff03f76e778f890c18147900b4540af124e93011

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - pillow
    - pywavelets
    - scipy
    - six

test:
  imports:
    - imagehash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JohannesBuchner/imagehash
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Perceptual Image Hahsing Module

extra:
  recipe-maintainers:
    - JohannesBuchner
    - bjlittle
    - ocefpaf
